config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :products
  resources :marketings
  resources :retailinforms
  resources :retailers
  get "welcome"=>"welcome#index"
  root :to =>"welcome#index"
  get "marketing/input" => "marketings#input"
  get "marketing/redirt" => "marketings#redirt"
  get "data" => 'materials#data'
  get "a" => 'materials#a'
  get "b" => 'materials#b'

end

app/models/retailer.rb
class Retailer < ActiveRecord::Base
	validates_presence_of :p_id, message:"不可為空白"
	validates_numericality_of :number_sold, :only_integer => true,message:'請輸入整數'
	validates_numericality_of :number_bought, :only_integer => true,message:'請輸入整數'

end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  before_action :set_retailer, only: [:show, :edit, :update, :destroy]

  # GET /retailers
  # GET /retailers.json
  def index
    @retailers = Retailer.all
    @retailinforms =Retailinform.all
  end

  # GET /retailers/1
  # GET /retailers/1.json
  def show
  end

  # GET /retailers/new
  def new
    @retailer = Retailer.new
  end

  # GET /retailers/1/edit
  def edit
  end

  # POST /retailers
  # POST /retailers.json
  def create
    retailers_u="/retailers/new"
    @retailer = Retailer.new(retailer_params)
    @retailer.temp=@retailer.number_bought-@retailer.number_sold
    @retailer.save
    a=Retailinform.find_by(p_id: @retailer.p_id)
    if a==nil
      @retailer.destroy
      redirect_to retailers_u
      flash[:notice]="請先至門市基本資料新增一筆基本資料再回來新增庫存資料，或輸入已經存在的商品"
    else
      a.r_inventory=a.r_inventory+@retailer.temp
      a.save
      redirect_to @retailer
    end

  end

  # PATCH/PUT /retailers/1
  # PATCH/PUT /retailers/1.json
   def update
   # respond_to do |format|
   retailers_u="/retailers/new"
   k=@retailer.p_id_was
      b=@retailer.number_bought-@retailer.number_sold
        @retailer.update(retailer_params)
        @retailer.temp=@retailer.number_bought-@retailer.number_sold
      a=Retailinform.find_by(p_id: @retailer.p_id)
    if a==nil
      @retailer.p_id=k
      @retailer.save
      redirect_to @retailer
      flash[:notice]="更新無效，請先至門市基本資料新增一筆基本資料再回來更改庫存資料，或輸入已經存在的商品"
    else
      a.r_inventory=a.r_inventory+@retailer.temp-b
      a.save
      redirect_to @retailer

    end

    #  else
    #    format.html { render :edit }
    #    format.json { render json: @retailer.errors, status: :unprocessable_entity }
    #  end
   # end
  end

  # DELETE /retailers/1
  # DELETE /retailers/1.json
  def destroy
    b=@retailer.number_bought-@retailer.number_sold
    a=Retailinform.find_by(p_id: @retailer.p_id)
    a.r_inventory=a.r_inventory-b
    a.save
    @retailer.destroy
    respond_to do |format|
      format.html { redirect_to retailers_url, notice: 'Retailer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retailer
      @retailer = Retailer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def retailer_params
      params.require(:retailer).permit(:p_id, :p_name, :number_sold, :number_bought, :valid_date, :temp)
    end
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/retailers/_form.html.erb
<%= form_for(@retailer) do |f| %>
  <% if @retailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@retailer.errors.count, "error") %> prohibited this retailer from being saved:</h2>

      <ul>
      <% @retailer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :產品編號 %><br>
    <%= f.text_field :p_id %>
  </div>
  <div class="field">
    <%= f.label :產品名稱 %><br>
    <%= f.text_field :p_name %>
  </div>
  <div class="field">
    <%= f.label :賣出數量 %><br>
    <%= f.number_field :number_sold %>
  </div>
  <div class="field">
    <%= f.label :進貨量 %><br>
    <%= f.number_field :number_bought %>
  </div>
  <div class="field">
    <%= f.label :有效日期 %><br>
    <%= f.date_select :valid_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/retailers/edit.html.erb
<h1>編輯門市庫存</h1>

<%= render 'form' %>

<%= link_to '秀', @retailer %> |
<%= link_to '回到上一頁', retailers_path %>

app/views/retailers/index.html.erb
<!--存貨量不足的警示-->
<% @retailinforms.each do |retailinform| %>
  <%if retailinform.r_inventory>retailinform.rop%>
    
  <%else%>
  <!--最上方警示-->
    <div class="alert alert-danger in fade" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      存貨量太少
    </div>
  <!--左方警示-->
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
          })
    </script>
 <%end%>
<%end%>

<!--警示結束-->


<h1>門市庫存管理</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>產品編號</th>
      <th>產品名稱</th>
      <th>賣出數量</th>
      <th>進貨量</th>
      <th>有效日期</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @retailers.each do |retailer| %>
      <tr>
        <td><%= retailer.p_id %></td>
        <td><%= retailer.p_name %></td>
        <td><%= retailer.number_sold %></td>
        <td><%= retailer.number_bought %></td>
        <td><%= retailer.valid_date %></td>
        <td><%= link_to '秀', retailer %></td>
        <td><%= link_to '編輯', edit_retailer_path(retailer) %></td>
        <td><%= link_to '刪除', retailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type=button class="btn btn-lg btn-default"><%= link_to '新增門市庫存', new_retailer_path %></button>

<h1>庫存基本資料管理</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th >產品編號</th>
      <th >預估每週最大需求</th>
      <th >預估每週最小需求</th>
      <th >訂購成本</th>
      <th >持有成本</th>
      <th >總成本</th>
      <th >售價</th>
      <th>存貨量</th>
      <th>建議訂購數量</th>
      <th>再訂購點</th>
      <th>存量狀況</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @retailinforms.each do |retailinform| %>
      <tr>
        <td><%= retailinform.p_id %></td>
        <td><%= retailinform.max_demand %></td>
        <td><%= retailinform.min_demand %></td>
        <td><%= retailinform.book_cost %></td>
        <td><%= retailinform.hold_cost %></td>
        <td><%= retailinform.cost %></td>
        <td><%= retailinform.price %></td>
        <td><%= retailinform.r_inventory %></td>
        <td><%= retailinform.eoq.round(2) %></td>
        <td><%= retailinform.rop.round(2) %></td>
        <td><%if retailinform.r_inventory>retailinform.rop%>
        ok
        <%else%>
        <div style="color:red" data-toggle="tooltip" title="請趕緊訂購!!" data-placement="left">
        Not ok
        </div>
        <%end%>
        </td>
        <td><%= link_to '秀', retailinform %></td>
        <td><%= link_to '編輯', edit_retailinform_path(retailinform) %></td>
        <td><%= link_to '刪除', retailinform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type=button class="btn btn-lg btn-default"><%= link_to '新增庫存基本資料', new_retailinform_path %></button>

<button type=button class="btn btn-lg btn-default"><%= link_to "回到首頁" , root_path%></button>

app/views/retailers/new.html.erb
<h1>新增門市庫存</h1>

<%= render 'form' %>

<%= link_to '回到上一頁', retailers_path %>

app/views/retailers/show.html.erb
<p id="notice"><%= notice %></p>
<h1>門市庫存資料</h1>
<p>
  <strong>產品編號:</strong>
  <%= @retailer.p_id %>
</p>

<p>
  <strong>產品名稱:</strong>
  <%= @retailer.p_name %>
</p>

<p>
  <strong>賣出數量:</strong>
  <%= @retailer.number_sold %>
</p>

<p>
  <strong>進貨量:</strong>
  <%= @retailer.number_bought %>
</p>

<p>
  <strong>有效日期:</strong>
  <%= @retailer.valid_date %>
</p>

<%= link_to '編輯', edit_retailer_path(@retailer) %> |
<%= link_to '回到上一頁', retailers_path %>