config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :products
  resources :marketings
  resources :retailinforms
  resources :retailers
  get "welcome"=>"welcome#index"
  root :to =>"welcome#index"
  get "marketing/input" => "marketings#input"
  get "marketing/redirt" => "marketings#redirt"
  get "data" => 'materials#data'
  get "a" => 'materials#a'
  get "b" => 'materials#b'

end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end
def data
    @materials = Material.all
  end
  def a
    @materials = Material.all
  end
  def b
    @materials = Material.all
  end
  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit

  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
     mater="/data"
    
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to mater, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    mater="/data"
    @material.destroy
    respond_to do |format|
      format.html { redirect_to mater, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:m_id, :m_name, :m_cost, :supplier, :transportation_time, :number, :result, :quality, :s_address, :s_phone, :condition)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--div class="field">
    <%= f.label :m_id %><br>
    <%= f.text_field :m_id %>
  </div>
  <div class="field">
    <%= f.label :m_name %><br>
    <%= f.text_field :m_name %>
  </div>
  <div class="field">
    <%= f.label :m_cost %><br>
    <%= f.number_field :m_cost %>
  </div>
  <div class="field">
    <%= f.label :supplier %><br>
    <%= f.text_field :supplier %>
  </div>
  <div class="field">
    <%= f.label :s_address %><br>
    <%= f.text_field :s_address %>
  </div>
  <div class="field">
    <%= f.label :s_phone %><br>
    <%= f.number_field :s_phone %>
  </div>
  <div class="field">
    <%= f.label :transportation_time %><br>
    <%= f.number_field :transportation_time %>
  </div>
    <div class="field">
    <%= f.label :quality %><br>
    <%= f.number_field :quality %>
  </div>
   <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div-->
  <div class="field">
    <%= f.label :製造數量 %><br>
    <%= f.number_field :number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/a.html.erb
<table class="table">
  <thead>
    <tr>
      <th>產品編號</th>
      <th>原料名稱</th>
      <th>原料成本</th>
      <th>供應商</th>
      <th>運送時間(日)</th>
      <th>訂購數量</th>
      <th>訂購時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <% if material.result=='小泡芙' && material.quality == 1%>
        <td><%= material.m_id %></td>
        <td><%= material.m_name %></td>
        <td><%= material.m_cost %></td>
        <td><%= material.supplier %></td>
        <td><%= material.transportation_time %></td>
        <td><%= material.number %></td>
         <td><%= material.updated_at.in_time_zone("Taipei") %></td>
        <td><%= link_to '資料一覽', material %></td>
        <td><%= link_to '編輯購買量', edit_material_path(material) %></td>
        
      <% else %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<button type=button class="btn btn-lg btn-default"> <%= link_to '生產系統', products_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '合格原料表', materials_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '原料資料庫', data_path %></button>

app/views/materials/b.html.erb
<table class="table">
  <thead>
    <tr>
      <th>產品編號</th>
      <th>原料名稱</th>
      <th>原料成本</th>
      <th>供應商</th>
      <th>運送時間(日)</th>
      <th>訂購數量</th>
      <th>訂購時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <% if material.result=='牛奶' && material.quality == 1%>
        <td><%= material.m_id %></td>
        <td><%= material.m_name %></td>
        <td><%= material.m_cost %></td>
        <td><%= material.supplier %></td>
        <td><%= material.transportation_time %></td>
        <td><%= material.number %></td>
         <td><%= material.updated_at.in_time_zone("Taipei") %></td>
        <td><%= link_to '資料一覽', material %></td>
        <td><%= link_to '編輯購買量', edit_material_path(material) %></td>
        
      <% else %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<button type=button class="btn btn-lg btn-default"> <%= link_to '生產系統', products_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '合格原料表', materials_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '原料資料庫', data_path %></button>

app/views/materials/data.html.erb
<p id="notice"><%= notice %></p>

<h1>原料資料庫</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>原料名稱</th>
      <th>原料成本</th>
      <th>供應商</th>
      <th>供應商住址</th>
      <th>供應商電話</th>
      <th>運送時間(日)</th>
      <th>製成品</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.m_id %></td>
        <td><%= material.m_name %></td>
        <td><%= material.m_cost %></td>
        <td><%= material.supplier %></td>
        <td><%= material.s_address %></td>
        <td><%= material.s_phone %></td>
        <td><%= material.transportation_time %></td>
        <td><%= material.result %></td>
        <td><%= link_to '秀', material %></td>
        <td><%= link_to '編輯', edit_material_path(material) %></td>
        <td><%= link_to '刪除', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type=button class="btn btn-lg btn-default"><%= link_to '新增原料', new_material_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '生產系統', products_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '合格原料', materials_path %></button>

app/views/materials/edit.html.erb
<h1>編輯原料</h1>

<%= render 'form' %>

<%= link_to '秀', @material %> |
<%= link_to '回到上一頁', data_path %>

app/views/materials/index.html.erb
<h1>合格原料</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>原料名稱</th>
      <th>原料成本</th>
      <th>供應商</th>
      <th>運送時間(日)</th>
      <th>訂購數量</th>
      <th>製成品</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
       <% if material.quality == 1 %>
        <td><%= material.m_id %></td>
        <td><%= material.m_name %></td>
        <td><%= material.m_cost %></td>
        <td><%= material.supplier %></td>
        <td><%= material.transportation_time %></td>
        <td><%= material.number %></td>
        <td><%= material.result %></td>
        <td><%= link_to '原料明細', material %></td>
       <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type=button class="btn btn-lg btn-default"><%= link_to '生產小泡芙', a_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '生產牛奶', b_path %></button><br><br>
<button type=button class="btn btn-lg btn-default"><%= link_to '生產系統', products_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '原料資料庫', data_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '回首頁', root_path %></button>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>M:</strong>
  <%= @material.m_id %>
</p>

<p>
  <strong>原料名稱</strong>
  <%= @material.m_name %>
</p>

<p>
  <strong>原料成本</strong>
  <%= @material.m_cost %>
</p>

<p>
  <strong>供應商</strong>
  <%= @material.supplier %>
</p>

<p>
  <strong>供應商地址</strong>
  <%= @material.s_address %>
</p>

<p>
  <strong>供應商電話</strong>
  <%= @material.s_phone %>
</p>
<p>
  <strong>運輸時間</strong>
  <%= @material.transportation_time %>
</p>


<p>
  <strong>製成品</strong>
  <%= @material.result %>
</p>

<button type=button class="btn btn-lg btn-default"><%= link_to '編輯', edit_material_path(@material) %></button> 
<button type=button class="btn btn-lg btn-default"><%= link_to '合格原料', materials_path %></button>
<button type=button class="btn btn-lg btn-default"><%= link_to '原料資料庫', data_path %></button>